# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import movieapi_pb2 as movieapi__pb2


class Movie_RecommendationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Movie_Recommendation_by_cnn = channel.unary_unary(
                '/movieapi.Movie_Recommendation/Movie_Recommendation_by_cnn',
                request_serializer=movieapi__pb2.MovieRecommendation.SerializeToString,
                response_deserializer=movieapi__pb2.RecommendedMovies_Array.FromString,
                )


class Movie_RecommendationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Movie_Recommendation_by_cnn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Movie_RecommendationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Movie_Recommendation_by_cnn': grpc.unary_unary_rpc_method_handler(
                    servicer.Movie_Recommendation_by_cnn,
                    request_deserializer=movieapi__pb2.MovieRecommendation.FromString,
                    response_serializer=movieapi__pb2.RecommendedMovies_Array.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movieapi.Movie_Recommendation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Movie_Recommendation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Movie_Recommendation_by_cnn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/movieapi.Movie_Recommendation/Movie_Recommendation_by_cnn',
            movieapi__pb2.MovieRecommendation.SerializeToString,
            movieapi__pb2.RecommendedMovies_Array.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
