# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movieapi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emovieapi.proto\x12\x08movieapi\"G\n\x13MovieRecommendation\x12\x11\n\tmoviename\x18\x01 \x01(\t\x12\x1d\n\x15no_of_recommendations\x18\x02 \x01(\x05\"5\n\x17RecommendedMovies_Array\x12\x1a\n\x12Recommended_Movies\x18\x01 \x03(\t2y\n\x14Movie_Recommendation\x12\x61\n\x1bMovie_Recommendation_by_cnn\x12\x1d.movieapi.MovieRecommendation\x1a!.movieapi.RecommendedMovies_Array\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movieapi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVIERECOMMENDATION._serialized_start=28
  _MOVIERECOMMENDATION._serialized_end=99
  _RECOMMENDEDMOVIES_ARRAY._serialized_start=101
  _RECOMMENDEDMOVIES_ARRAY._serialized_end=154
  _MOVIE_RECOMMENDATION._serialized_start=156
  _MOVIE_RECOMMENDATION._serialized_end=277
# @@protoc_insertion_point(module_scope)
